version: 1
update_configs:
- package_manager: 'dotnet:nuget'
  directory: '/Logic/Logic.Models'
  update_schedule: 'live'
- package_manager: 'dotnet:nuget'
  directory: '/Logic.Logic.Core'
  update_schedule: 'live'