version: 1
update-configs:
- package-manager: 'dotnet:nuget'
  directory: '/Logic/Logic.Models'
  update-schedule: 'live'
- package-manager: 'dotnet:nuget'
  directory: '/Logic.Logic.Core'
  update-schedule: 'live'