name: "CoffeeCup Logic CI/CD"

on:
  pull_request:
    branches: [main]
    paths:
      - "src/Logic/Logic.Core/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          cache: false
          cache-dependency-path: src/Logic/Logic.Core/packages.lock.json
      - run: dotnet restore src/Logic/Logic.Core/Logic.Core.csproj
      - name: Build
        run: dotnet build src/Logic/Logic.Core/Logic.Core.csproj
        env:
          working-directory: "src/Logic/Logic.Core"
      - name: Package
        run: dotnet pack src/Logic/Logic.Core/Logic.Core.csproj -c Release -o src/Logic/Logic.Core/packs
        env:
          working-directory: "src/Logic/Logic.Core"
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: "src/Logic/Logic.Core/packs/*.*"
  publish:
    needs: build
    environment: "nuget"
    runs-on: ubuntu-latest
    env:
      working-directory: "src/Logic/Logic.Core"
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: "."
      - name: Publish Models to Nuget
        run: |
          nupkg=$(find . -type f -name "*.nupkg" | head -n 1)
          snupkg=$(find . -type f -name "*.snupkg" | head -n 1)
          dotnet nuget push $nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }} --skip-duplicate
